export const fakeData = [
  {
    id: 1,
    name: "Tanoodle",
    type: "Full Refund",
    coverage: "972",
    paymentMode: "yearly",
    stampFee: 79,
    policyTerm: 12,
    total: 2587441,
    surrenderValue: "False",
    premiumValue: "True",
    coverageFromDayOne: "False",
    images:
      "https://www.ttifc.co.tt/web/wp-content/uploads/2020/12/motor-one.png",
    premium: 3748,
    ratting: 2,
  },
  {
    id: 2,
    name: "Oozz",
    type: "Not Refund",
    coverage: "4056",
    paymentMode: "monthly",
    stampFee: 94,
    policyTerm: 12,
    total: 5086931,
    surrenderValue: "False",
    premiumValue: "True",
    coverageFromDayOne: "True",
    images:
      "https://allresultbd.com/wp-content/uploads/2015/05/Bangladesh-National-Insurance.jpg",
    premium: 3523,
    ratting: 2,
  },
  {
    id: 3,
    name: "Roomm",
    type: "Not Refund",
    coverage: "2904",
    paymentMode: "yearly",
    stampFee: 57,
    policyTerm: 12,
    total: 12595750,
    surrenderValue: "False",
    premiumValue: "True",
    coverageFromDayOne: "False",
    images: "http://asthalife.com.bd/assets/images/Astha-Life.png",
    premium: 2488,
    ratting: 2,
  },
  {
    id: 4,
    name: "Meembee",
    type: "Not Refund",
    coverage: "9",
    paymentMode: "yearly",
    stampFee: 63,
    policyTerm: 12,
    total: 8181669,
    surrenderValue: "False",
    premiumValue: "False",
    coverageFromDayOne: "False",
    images:
      "https://www.ttifc.co.tt/web/wp-content/uploads/2020/12/motor-one.png",
    premium: 3864,
    ratting: 1,
  },
  {
    id: 5,
    name: "Mymm",
    type: "Full Refund",
    coverage: "3",
    paymentMode: "yearly",
    stampFee: 86,
    policyTerm: 12,
    total: 17740565,
    surrenderValue: "False",
    premiumValue: "True",
    coverageFromDayOne: "False",
    images:
      "https://www.ttifc.co.tt/web/wp-content/uploads/2020/12/motor-one.png",
    premium: 4178,
    ratting: 5,
  },
  {
    id: 6,
    name: "Photobug",
    type: "Not Refund",
    coverage: "1742",
    paymentMode: "weekly",
    stampFee: 75,
    policyTerm: 12,
    total: 7033660,
    surrenderValue: "False",
    premiumValue: "False",
    coverageFromDayOne: "True",
    images:
      "https://allresultbd.com/wp-content/uploads/2015/05/Bangladesh-National-Insurance.jpg",
    premium: 1980,
    ratting: 4,
  },
  {
    id: 7,
    name: "Topdrive",
    type: "Full Refund",
    coverage: "7",
    paymentMode: "yearly",
    stampFee: 53,
    policyTerm: 12,
    total: 18096409,
    surrenderValue: "False",
    premiumValue: "False",
    coverageFromDayOne: "False",
    images:
      "https://allresultbd.com/wp-content/uploads/2015/05/Bangladesh-National-Insurance.jpg",
    premium: 2163,
    ratting: 1,
  },
  {
    id: 8,
    name: "Yozio",
    type: "Not Refund",
    coverage: "50",
    paymentMode: "weekly",
    stampFee: 94,
    policyTerm: 12,
    total: 11259711,
    surrenderValue: "False",
    premiumValue: "True",
    coverageFromDayOne: "True",
    images: "http://asthalife.com.bd/assets/images/Astha-Life.png",
    premium: 1097,
    ratting: 3,
  },
  {
    id: 9,
    name: "Twitternation",
    type: "Not Refund",
    coverage: "39",
    paymentMode: "yearly",
    stampFee: 62,
    policyTerm: 12,
    total: 12613480,
    surrenderValue: "False",
    premiumValue: "False",
    coverageFromDayOne: "True",
    images:
      "https://www.ttifc.co.tt/web/wp-content/uploads/2020/12/motor-one.png",
    premium: 3974,
    ratting: 1,
  },
  {
    id: 10,
    name: "Brainlounge",
    type: "Full Refund",
    coverage: "156",
    paymentMode: "weekly",
    stampFee: 50,
    policyTerm: 12,
    total: 12770299,
    surrenderValue: "False",
    premiumValue: "True",
    coverageFromDayOne: "True",
    images:
      "https://www.ttifc.co.tt/web/wp-content/uploads/2020/12/motor-one.png",
    premium: 3235,
    ratting: 5,
  },
];
